root = "."
tmp_dir = ".air"

[build]
  cmd = "go build -o ./.air/main ./cmd/api"
  bin = ".air/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", ".git", "tmp", ".air"]
  delay = 200

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
